In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('Ecommerce Purchases')
data

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

In [3]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [4]:
data["Lot"].str.split(" ").str[1].unique()

array(['in', 'rn', 'vE', ..., 'HW', 'UD', 'rU'],
      shape=(2649,), dtype=object)

In [5]:
data["Lot"].head(10)

0    46 in
1    28 rn
2    94 vE
3    36 vm
4    20 IE
5    21 XT
6    96 Xt
7    96 pG
8    45 JN
9    15 Ug
Name: Lot, dtype: object

### 1. Display Top 10 Rows of The Dataset

In [6]:
data.head(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
5,"7502 Powell Mission Apt. 768\nTravisland, VA 3...",21 XT,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_5...,Silva-Anderson,30246185196287,07/25,7169,Discover,ynguyen@gmail.com,Fish farm manager,55.96.152.147,ru,25.15
6,"93971 Conway Causeway\nAndersonburgh, AZ 75107",96 Xt,AM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Gibson and Sons,6011398782655569,07/24,714,VISA 16 digit,olivia04@yahoo.com,Dancer,127.252.144.18,de,88.56
7,"260 Rachel Plains Suite 366\nCastroberg, WV 24...",96 pG,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5350...,Marshall-Collins,561252141909,06/25,256,VISA 13 digit,phillip48@parks.info,Event organiser,224.247.97.150,pt,44.25
8,"2129 Dylan Burg\nNew Michelle, ME 28650",45 JN,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Galloway and Sons,180041795790001,04/24,899,JCB 16 digit,kdavis@rasmussen.com,Financial manager,146.234.201.229,ru,59.54
9,"3795 Dawson Extensions\nLake Tinafort, ID 88739",15 Ug,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...,"Rivera, Buchanan and Ramirez",4396283918371,01/17,931,American Express,qcoleman@hunt-huerta.com,Forensic scientist,236.198.199.8,zh,95.63

### 2. Check Last 10 Rows of The Dataset

In [7]:
data.tail(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
9990,"75731 Molly Springs\nWest Danielle, VT 96934-5102",93 ty,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_4;...,"Pace, Vazquez and Richards",869968197049750,04/24,877,JCB 15 digit,andersonmichael@sherman.biz,Early years teacher,54.170.3.185,ru,18.35
9991,"PSC 8165, Box 8498\nAPO AP 60327-0346",50 dA,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Snyder Inc,4221582137197481,02/24,969,Voyager,kking@wise-liu.com,IT sales professional,254.25.31.156,el,25.93
9992,"885 Allen Mountains Apt. 230\nWallhaven, LA 16995",40 vH,PM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_6_5) A...,Wells Ltd,4664825258997302,10/20,431,Discover,bberry@wright.net,Set designer,174.173.51.32,de,67.96
9993,"7555 Larson Locks Suite 229\nEllisburgh, MA 34...",72 jg,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...,Colon and Sons,30025560104631,10/25,629,Maestro,chelseawilliams@lopez.biz,"Designer, exhibition/display",177.46.82.128,el,65.61
9994,"6276 Rojas Hollow\nLake Louis, WY 56410-7837",93 Ex,PM,Opera/9.68.(X11; Linux x86_64; sl-SI) Presto/2...,Ritter-Smith,3112186784121077,01/25,1823,Maestro,iroberts@gmail.com,"Education officer, museum",242.44.112.18,zh,31.85
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

### 3. Check Datatype of Each Column

In [8]:
data.dtypes

Address              object
Lot                  object
AM or PM             object
Browser Info         object
Company              object
Credit Card           int64
CC Exp Date          object
CC Security Code      int64
CC Provider          object
Email                object
Job                  object
IP Address           object
Language             object
Purchase Price      float64
dtype: object

### 4. Check null values in the dataset

In [9]:
data.isnull().sum()

Address             0
Lot                 0
AM or PM            0
Browser Info        0
Company             0
Credit Card         0
CC Exp Date         0
CC Security Code    0
CC Provider         0
Email               0
Job                 0
IP Address          0
Language            0
Purchase Price      0
dtype: int64

### 5. How many rows and columns are there in our Dataset?

In [10]:
data.shape #(row , col)

(10000, 14)

In [39]:
len(data)

10000

In [40]:
len(data.columns)

14

### 6. Highest and Lowest Purchase Prices.

In [11]:
data[data["Purchase Price"] == data["Purchase Price"].max()]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
2092,"63773 Shelton Greens\nAshleyton, MA 00493",56 lu,AM,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,Pitts Group,4292741269160,06/18,824,Maestro,heatherwoodard@lloyd.com,"Surveyor, hydrographic",172.197.216.229,el,99.99
7807,"PSC 6177, Box 1004\nAPO AA 57143-1269",64 Nf,AM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_4)...,"Porter, Johnson and Pratt",30109394842259,11/25,918,VISA 16 digit,kelli72@gmail.com,"Surveyor, insurance",89.51.92.242,de,99.99

In [12]:
pd.DataFrame (data.loc[data["Purchase Price"].idxmax()])

                                                               2092
Address                   63773 Shelton Greens\nAshleyton, MA 00493
Lot                                                           56 lu
AM or PM                                                         AM
Browser Info      Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...
Company                                                 Pitts Group
Credit Card                                           4292741269160
CC Exp Date                                                   06/18
CC Security Code                                                824
CC Provider                                                 Maestro
Email                                      heatherwoodard@lloyd.com
Job                                          Surveyor, hydrographic
IP Address                                          172.197.216.229
Language                                                         el
Purchase Price                                                99.99

In [13]:
data.loc[data["Purchase Price"].idxmax() , ["Email" , "Address"]]

Email                       heatherwoodard@lloyd.com
Address    63773 Shelton Greens\nAshleyton, MA 00493
Name: 2092, dtype: object

In [14]:
data[["Email" , "Address"]][data["Purchase Price"] == data["Purchase Price"].max()]

                         Email                                    Address
2092  heatherwoodard@lloyd.com  63773 Shelton Greens\nAshleyton, MA 00493
7807         kelli72@gmail.com      PSC 6177, Box 1004\nAPO AA 57143-1269

In [15]:
data["Purchase Price"].min()

np.float64(0.0)

In [16]:
data[data["Purchase Price"] == data["Purchase Price"].min()]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
2876,"332 Jones Parkways\nEast Katherineville, GA 64230",39 GT,AM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_6_9...,"Lyons, Diaz and Clark",4204500444841766,01/18,38,VISA 16 digit,jennifer11@baker.com,Biomedical scientist,223.47.177.174,it,0.0
5487,"465 Mallory Ways\nNorth Rebecca, RI 82734-1160",93 OH,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.6.20) Gec...,Flynn and Sons,30469912089738,09/23,236,Discover,mjohnson@austin.org,Stage manager,43.99.56.59,zh,0.0

### 7. Average Purchase Price

In [17]:
data['Purchase Price'].mean()

np.float64(50.347302)

### 8. How many people have French 'fr' as their Language?

In [18]:
data["Language"]

0       el
1       fr
2       de
3       es
4       es
        ..
9995    it
9996    pt
9997    el
9998    es
9999    el
Name: Language, Length: 10000, dtype: object

In [19]:
data.groupby("Language")["Language"].count()["fr"]

np.int64(1097)

In [20]:
data[data["Language"] == "fr"].value_counts("Language")

Language
fr    1097
Name: count, dtype: int64

In [21]:
(data["Language"] == "fr").sum()

np.int64(1097)

In [41]:
len(data[data["Language"] == "fr"])

1097

In [22]:
data.groupby("Language").size()

Language
de    1155
el    1137
en    1098
es    1095
fr    1097
it    1086
pt    1118
ru    1155
zh    1059
dtype: int64

### 9. Job Title Contains Engineer

In [23]:
data["Job"]

0       Scientist, product/process development
1                            Drilling engineer
2                     Customer service manager
3                            Drilling engineer
4                                  Fine artist
                         ...
9995                                Printmaker
9996                           Energy engineer
9997                        Veterinary surgeon
9998                  Local government officer
9999                    Embryologist, clinical
Name: Job, Length: 10000, dtype: object

In [24]:
data["Job"].nunique()

623

In [25]:
data["Job"].str.contains("Engineer", na=False)

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Name: Job, Length: 10000, dtype: bool

In [26]:
data[data["Job"].str.contains("Engineer", na=False)]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
55,"27635 Maureen Bypass Apt. 883\nSandraview, SD ...",59 LJ,AM,Mozilla/5.0 (iPod; U; CPU iPhone OS 3_3 like M...,Sims-Lyons,3158113629128344,09/19,857,VISA 16 digit,adkinsarthur@yahoo.com,"Engineer, broadcasting (operations)",227.235.89.210,pt,48.74
60,"7126 Katherine Squares\nPerkinsview, CO 97299-...",63 qu,AM,Opera/8.68.(X11; Linux x86_64; en-US) Presto/2...,Marshall-Fernandez,349767747049645,05/20,672,JCB 15 digit,sweeneyhannah@jones.biz,"Engineer, agricultural",197.144.142.102,de,20.43
64,"937 Weaver Isle Apt. 096\nTracyborough, KY 182...",97 QO,AM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_6_2 rv...,Villa Inc,869930676434762,11/21,578,Discover,jason24@gardner-anderson.com,"Engineer, civil (consulting)",218.171.210.9,it,72.45
82,493 Smith Valleys Suite 004\nNew Madelineville...,35 ls,PM,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_0 like M...,"Robinson, Johnston and Valdez",4351359627548412,06/17,937,VISA 13 digit,amendez@yahoo.com,"Engineer, materials",163.129.163.100,fr,49.04
92,Unit 9659 Box 0618\nDPO AA 00377-5360,37 jN,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,"Williams, Goodman and Morris",4748275281424579,01/18,496,JCB 15 digit,psimmons@harrison-brown.info,"Engineer, land",10.172.75.245,zh,73.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9868,Unit 9129 Box 2546\nDPO AP 96513,78 Ei,AM,Mozilla/5.0 (X11; Linux x86_64; rv:1.9.6.20) G...,Fowler-Villanueva,377635852162559,10/16,672,American Express,maryward@lane-reed.com,"Engineer, building services",101.29.252.241,de,25.88
9922,"0850 Joseph Estate Apt. 649\nNew Brookefort, K...",82 SJ,AM,Opera/8.29.(Windows NT 5.01; sl-SI) Presto/2.9...,"Anderson, Charles and Alexander",676344664773,12/19,572,VISA 16 digit,keith96@ross-garrett.info,"Engineer, electrical",225.184.17.88,fr,68.13
9925,"09281 Mills Court Apt. 022\nWatkinstown, WI 83...",15 PM,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5342...,Parker PLC,4872299411791,11/22,974,Diners Club / Carte Blanche,xholloway@cook-coleman.info,"Engineer, materials",175.188.141.23,fr,91.75
9945,"693 Gomez Keys\nWest Marcushaven, SC 32366-3890",60 tG,PM,Mozilla/5.0 (Windows NT 6.2) AppleWebKit/5350 ...,Clay-Johnson,4474423068651820,10/17,216,JCB 15 digit,kyle97@gmail.com,"Engineer, materials",123.237.158.173,pt,51.68
9952,"9991 Vaughn Hills\nRacheltown, PA 55409",36 KC,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,"Ward, Smith and Castillo",6011679271321726,09/19,964,Voyager,jonesjennifer@olson.com,"Engineer, energy",116.228.12.42,es,39.63

In [42]:
len(data[data["Job"].str.contains("Engineer", na=False,case=False)])

984

### 10. Find The Email of the person with the following IP Address: 132.207.160.22

In [28]:
data["Email"][data["IP Address"] == '132.207.160.22']

2    amymiller@morales-harrison.com
Name: Email, dtype: object

### 11. How many People have Mastercard as their Credit Card Provider and made a purchase above 50?

In [29]:
((data["CC Provider"] == 'Mastercard') & (data["Purchase Price"] > 50)).sum()

np.int64(405)

### 12. Find the email of the person with the following Credit Card Number: 4664825258997302

In [43]:
data["Email"][data["Credit Card"] == 4664825258997302]

9992    bberry@wright.net
Name: Email, dtype: object

In [31]:
data[data["Credit Card"] == '4664825258997302']

Empty DataFrame
Columns: [Address, Lot, AM or PM, Browser Info, Company, Credit Card, CC Exp Date, CC Security Code, CC Provider, Email, Job, IP Address, Language, Purchase Price]
Index: []

### 13. How many people purchase during the AM and how many people purchase during PM?

In [32]:
(data["AM or PM"] == "AM").sum()

np.int64(4932)

In [33]:
(data["AM or PM"] == "PM").sum()

np.int64(5068)

### 14. How many people have a credit card that expires in 2020?

In [34]:
data["CC Exp Date"]

0       02/20
1       11/18
2       08/19
3       02/24
4       10/25
        ...
9995    03/22
9996    07/25
9997    05/21
9998    11/17
9999    02/19
Name: CC Exp Date, Length: 10000, dtype: object

In [35]:
(data["CC Exp Date"].str.split('/').str[1] == "20").sum()

np.int64(988)

In [36]:
(data["CC Exp Date"].str[-2:] == "20").sum()

np.int64(988)

In [37]:
data["CC Exp Date"].str.endswith("20").sum()

np.int64(988)

### 15. What are the top 5 most popular email providers (e.g. gmail.com, yahoo.com, etc...)

In [38]:
data["Email"].str.split('@').str[1].value_counts().head()

Email
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: count, dtype: int64